name: gk_ble_device_flutter
description: "Bloc-based Flutter library to communicate with GK Concept devices via Bluetooth"
version: 1.0.0
homepage: https://www.github.com/GK-Concept/gk_ble_device_flutter

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  flutter_bloc: ^8.1.5
  logging: ^1.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
